name: layrz_icons_example
description: "Demonstrates how to use the layrz_icons plugin."
publish_to: 'none'

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter

  layrz_icons:
    path: ../

  layrz_theme: ^7.5.17
  layrz_models: any
  go_router: ^17.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

dependency_overrides:
  layrz_icons:
    path: ../