name: layrz_icons_example
description: "Demonstrates how to use the layrz_icons plugin."
publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  layrz_icons:
    path: ../

  layrz_theme: ^7.0.10
  layrz_models: any
  go_router: ^12.1.1
  url_launcher: ^6.3.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
