name: layrz_icons
description: "A unified icon package."
version: 1.0.0
homepage: https://github.com/goldenm-software/layrz_icons

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  
  material_design_icons_flutter: ^7.0.7296
  solar_icons: ^0.0.5
  font_awesome_flutter: ^10.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
