name: layrz_icons
description: "A unified icon package to simplify icon usage."
version: 1.0.4
homepage: https://icons.layrz.com
repository: https://github.com/goldenm-software/layrz_icons

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  
  material_design_icons_flutter: ^7.0.7296
  solar_icons: ^0.0.5
  font_awesome_flutter: ^10.8.0
  ionicons: ^0.2.2
  iconsax_plus: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
